version: "3.8"

services:
  database:
    container_name: database_${PROJECT_NAME}
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devuser
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./${PROJECT_NAME}:/var/www/html
    depends_on:
      - database
  nginx:
    container_name: nginx_${PROJECT_NAME}
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./${PROJECT_NAME}:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  phpmyadmin:
    container_name: phpmyadmin_${PROJECT_NAME}
    image: phpmyadmin:5.2-apache
    restart: always
    ports:
      - 9005:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=64M
